  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 5.0
  static_map: true
  origin_x: -10.0
  origin_y: -10.0
  origin_z: 0.0
  width: 20.0
  height: 20.0


  transform_tolerance: 0.1
  footprint: [[-0.285, 0.18], [-0.285, -0.18], [0.285, -0.18], [0.285, 0.18]]
  footprint_padding: 0.03

